name: wallust
pkgbuild_repo: swindlesmccoop/PKGBUILDs
source:
  repo: https://codeberg.org/explosion-mental/wallust.git
  releases: https://codeberg.org/api/v1/repos/explosion-mental/wallust/releases?limit=20
arch: x86_64
pkgbuild: wallust-bin
makedepends:
  - rust
build: |
  make
stage: |
  make install DESTDIR="$STAGING" PREFIX=/usr
